spring:
  thymeleaf:
    mode: HTML
#  profiles:
#    active: dev
  messages:
    basename: i18n/messages
    jpa:
      hibernate:
        ddl-auto: update
      show-sql: true

comment.avator: /images/avator.jpg
server:
  port: 80
# 阿里云通义千问配置
ai-key: sk-5e4131ddd09e406f9a5b656d000948b3

cosSecretId: AKIDb3MYtO0b4Tkt4OaYIn4RPGVaQ3RaUAhz
cosSecretKey: CQVPMHAyiMNaxWYXVft5KkGphnjZGDMR

