spring:
  datasource:
    url: jdbc:mysql://localhost:3306/smart-medicine?useUnicode=true&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
logging:
  level:
    root: warn
    cn.ming: info
  file: log/blog-pro.log

server:
  port: 8081

# 阿里云通义千问配置
ai-key: sk-5e4131ddd09e406f9a5b656d000948b3
